### ISSUE TITLE
Prettier

### ISSUE THREAD

**Issue by Edd-wordd** [Edd-wordd/echoSphere#30]
add prettier to project

**Comment by Fury-MadMax** [comment]
I want to work on this issue

**Comment by Edd-wordd** [comment]
Perfect, i generally keep it pretty simple. If we can keep it to 
{ "semi": false, "singleQuote": true, "tabWidth": 2, "printWidth": 100, "bracketSpacing": true } that would be ideal @Fury-MadMax
