### ISSUE TITLE
Add and Build a Component for the Copyright Footer

### ISSUE THREAD

**Issue by Edd-wordd** [Edd-wordd/echoSphere#66]
#### Description
We need to create a new component for the copyright footer that will be used across the application. This footer should be consistently styled and include dynamic content such as the current year and the company name. The new component should be built using best practices and integrated into the existing application layout.

#### Tasks
1. **Create a new `Footer` component:**
   - Develop a new React component named `Footer` in the `components` directory.
   - The component should include the text "Copyright © [Company Name] [Current Year]".
   - Ensure that the current year is dynamically generated.
   - Add prop validation for the company name to ensure it is always passed as a prop.

2. **Style the `Footer` component:**
   - Use CSS or a styling library (e.g., Material-UI, styled-components) to ensure the footer is visually consistent with the rest of the application.
   - The footer should be responsive and look good on both desktop and mobile devices.

3. **Integrate the `Footer` component:**
   - Add the `Footer` component to the main layout so that it appears on all pages.
   - Ensure that the footer does not interfere with existing content and is properly positioned at the bottom of the viewport or page.

4. **Write tests for the `Footer` component:**
   - Create unit tests to verify that the footer renders correctly with the provided company name and current year.
   - Ensure the tests cover edge cases, such as when no company name is provided.

5. **Update documentation:**
   - Add documentation for the new `Footer` component, including usage examples.
   - Update any relevant parts of the project documentation to reflect the addition of the footer.

#### Additional Notes
- Please follow the project's coding standards and guidelines.
- Ensure that the new component is accessible and follows best practices for accessibility.
- If you have any questions or need further clarification, feel free to reach out.

#### References
- [Material-UI Footer Example](https://material-ui.com/components/footers/)
- [Styled-components Documentation](https://styled-components.com/docs)

Thank you for contributing to our project!

**Comment by DevGajjar28** [comment]
@Edd-wordd can you assign me ?
